In [7]:
## Testing purpose ##
import numpy as np
import shap
import torch
import torch.nn as nn
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from explainer import Explainer

In [5]:
def main():
    # Create synthetic data
    np.random.seed(42)
    X = np.random.rand(100, 5)  # 100 samples, 5 features
    y = (X.sum(axis=1) > 2.5).astype(int)  # Binary target
    
    # Test 1: Tree model (Random Forest)
    print("Testing Tree Model Explainer...")
    rf = RandomForestClassifier(n_estimators=10, random_state=42)
    rf.fit(X, y)
    
    tree_explainer = shap.TreeExplainer(rf, X, model_output="probability")
    sv_tree = tree_explainer.shap_values(X[:5])
    print("Tree SHAP values (first 5 samples):")
    print(sv_tree[1])  # Show SHAP values for class 1
    
    # Test 2: Linear model (Logistic Regression)
    print("\nTesting Linear Model Explainer...")
    lr = LogisticRegression(random_state=42)
    lr.fit(X, y)
    
    linear_explainer = shap.LinearExplainer(lr, X)
    sv_linear = linear_explainer.shap_values(X[:5])
    print("\nLinear SHAP values (first 5 samples):")
    print(sv_linear)
    
    # Test 3: Neural Network (MLP Classifier)
    print("\nTesting Deep Model Explainer (MLP)...")
    mlp = MLPClassifier(hidden_layer_sizes=(10,), max_iter=500, random_state=42)
    mlp.fit(X, y)
    
    # Create a prediction function that outputs probabilities
    def mlp_predict(x):
        return mlp.predict_proba(x)
    
    # Use KernelExplainer for MLP (more stable than DeepExplainer for scikit-learn MLP)
    mlp_explainer = shap.KernelExplainer(mlp_predict, X[:50])  # Use 50 samples as background
    sv_mlp = mlp_explainer.shap_values(X[:5])
    print("\nMLP SHAP values (first 5 samples):")
    print(sv_mlp[1])  # Show SHAP values for class 1

In [8]:
if __name__ == "__main__":
    main()

Testing Tree Model Explainer...
Tree SHAP values (first 5 samples):
[[ 0.01561667  0.38020001  0.12336667  0.05436667 -0.07855   ]
 [-0.0921     -0.30051667  0.05365    -0.05251667 -0.01351667]
 [-0.29260001  0.1224      0.0289     -0.17393334 -0.18976667]
 [-0.05565    -0.1649     -0.01448333 -0.06565    -0.10431667]
 [-0.02661667 -0.14653334 -0.1012     -0.08978334 -0.04086667]]

Testing Linear Model Explainer...

Linear SHAP values (first 5 samples):
[[-0.1924061   0.78927122  0.60062715  0.13671834 -0.68476611]
 [-0.51543996 -0.86656322  0.9305281   0.14105727  0.58423175]
 [-0.71559052  0.82487905  0.84759076 -0.54563289 -0.62544551]
 [-0.47492506 -0.40993772  0.09111211 -0.15774564 -0.37395982]
 [ 0.15836766 -0.7155468  -0.48078824 -0.2735844   0.00495728]]

Testing Deep Model Explainer (MLP)...


Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.


  0%|          | 0/5 [00:00<?, ?it/s]


MLP SHAP values (first 5 samples):
[[-0.01816745  0.11344995  0.10312167  0.02988169 -0.11838843]
 [-0.06022757 -0.10547729  0.14888789  0.02740122  0.1031561 ]
 [-0.0760021   0.11141031  0.13705339 -0.06066243 -0.11150012]
 [-0.05369936 -0.04481844  0.00187594 -0.01120245 -0.07402276]
 [ 0.02018443 -0.08256092 -0.10043595 -0.02673163 -0.00262634]]
